#!/usr/bin/env node
/**
 * Propagates version.js to the places that cannot read it directly:
 *
 * - package.json                    "version"
 * - ios/Config/Version.xcconfig     MARKETING_VERSION / CURRENT_PROJECT_VERSION
 *
 * Android needs no step here: Gradle parses version.js itself.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const v = require(path.join(root, 'version.js'));

const pkgPath = path.join(root, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
pkg.version = v.version;
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

const xcconfigPath = path.join(root, 'ios', 'Config', 'Version.xcconfig');
fs.writeFileSync(
  xcconfigPath,
  [
    '// Generated by scripts/sync-version.js from version.js - do not edit.',
    `MARKETING_VERSION = ${v.version}`,
    `CURRENT_PROJECT_VERSION = ${v.versionCode}`,
    `APP_JS_VERSION = ${v.jsv}`,
    '',
  ].join('\n'),
);

console.log(
  `Synced package.json + iOS to v${v.version} (code ${v.versionCode}, jsv ${v.jsv})`,
);
